### ISSUE TITLE
getDefaultCategoryTreeId ReferenceError: isString is not defined 

### ISSUE THREAD

**Issue by mooSylla** [pajaydev/ebay-node-api#105]
Hello mate! 

The method "getDefaultCategoryTreeId" of the  Taxonomy-api is not working! 

**Original code** 
`
try{
      await ebay.getAccessToken()
      const data = await ebay.getDefaultCategoryTreeId(EbayMarketplace)
      console.log(data);
      return data;
    }catch(err){
      console.log(err)
    }
  }
`
**Error Message:**

`
ReferenceError: isString is not defined
    at Object.<anonymous> (/media/programming coding/programming workshop/NodeJS/Ebay Rewards/node_modules/ebay-node-api/src/common-utils/index.js:78:5)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/media/programming coding/programming workshop/NodeJS/Ebay Rewards/node_modules/ebay-node-api/src/buy-api.js:5:42)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
`

After some digging in the source code i've found out that `isString()` is not accessable via `upperCase()` 's scope. 

After making the tostring() available to upperCase() scope everything works fine since

**Comment by pajaydev** [comment]
@mooSylla  my bad,  Thanks for pointing this out. Cool I will review the PR, I appreciate it.

**Comment by mooSylla** [comment]
My pleasure @pajaydev, this is my first PR I'm very excited :) take all your time man.

**Comment by pajaydev** [comment]
@mooSylla  Closing this as u fixed it. Thanks. I will publish a new version
