### ISSUE TITLE
throws ERR_UNESCAPED_CHARACTERS when keyword contains spaced

### ISSUE THREAD

**Issue by simonwjackson** [pajaydev/ebay-node-api#39]
```js
ebay
   .searchItems({
      keyword: "nintendo switch"
   })
```

```bash
(node:669) UnhandledPromiseRejectionWarning: TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:115:13)
    at Object.request (https.js:289:10)
    at /sandbox/node_modules/ebay-node-api/src/request.js:45:33
    at new Promise (<anonymous>)
    at postRequest (/sandbox/node_modules/ebay-node-api/src/request.js:44:12)
    at Promise (/sandbox/node_modules/ebay-node-api/src/buy-api.js:58:9)
    at new Promise (<anonymous>)
    at Ebay.searchItems (/sandbox/node_modules/ebay-node-api/src/buy-api.js:57:12)
    at ebay.getAccessToken.then.data (/sandbox/src/index.js:17:8)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pajaydev** [comment]
Thanks @simonwjackson for reporting. It got fixed in version 2.5.6. Kindly do 
`yarn install ebay-node-api@2.5.6`
